### ISSUE TITLE
Link to deployed playbook in repo's description

### ISSUE THREAD

**Issue by VarunBarad** [obvious/engineering-playbook#1]
You can add a link to the deployed version of this playbook inside the description of the repository in GitHub

[https://engineering.obvious.in](https://engineering.obvious.in)

**Comment by pratul** [comment]
You have write access to the repo — feel free to make changes yourself. If you’re unsure of the changes, I’d recommend raising a PR with the changes and dropping a message in #engineering on Slack to get more eyes on the changes.
